name: riverpod_to_do_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.4
  freezed_annotation: ^2.1.0
  state_notifier: ^0.7.2+1
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.4
  go_router: ^6.5.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  test: ^1.22.0


flutter:

  
  uses-material-design: true


